#Heroku Production Environment Configuration

#Heroku Database Configuration
spring:
  datasource:
    url: jdbc:postgresql://ec2-3-224-164-189.compute-1.amazonaws.com:5432/d4tjkkhpa9up9m
 
    username: eprreodgikglep
    password: a87dd5453e66b29863bdf65f9672608e758ea665433ac9446683968cb151aa94
    
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
  
  #Mail Sender Configuration
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: dongjinmaster9@gmail.com
    password: hbhgtagbwdpcbaxe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            
#External URL Configuration

swagger-ui:
  url: https://dillipapi.herokuapp.com/swagger-ui.html

randomquote:
  url: https://api.quotable.io/random
  
pincode:
  url: https://api.postalpincode.in/
  
bankdetails:
  url: https://ifsc.razorpay.com/
  
universitydetails:
  url: http://universities.hipolabs.com/search
  
guessgender:
  url: https://api.genderize.io/?name=