#Heroku Production Environment Configuration

#Heroku Database Configuration
spring:
  datasource:
    url: jdbc:postgresql://ec2-35-173-207-244.compute-1.amazonaws.com:5432/d15t3bp3knc27r
 
    username: nszxjptbnhecfr
    password: fb7ef8fba8aa28ba0438e5d1e1c5bd9d6821a5e847912e8b4bbfbc8ae1d0b3e2
    
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
  
  #Mail Sender Configuration
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: dongjinmaster9@gmail.com
    password: hbhgtagbwdpcbaxe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            
#External URL Configuration

randomquote:
  url: https://api.quotable.io/random
  
pincode:
  url: https://api.postalpincode.in/
  
bankdetails:
  url: https://ifsc.razorpay.com/
  
universitydetails:
  url: http://universities.hipolabs.com/search